py_binary(
    default_python_version="PY3",
    name = "mnist_convolutional_network",
    srcs = ["mnist_convolutional_network.py"],
    srcs_version = "PY3",
)

py_binary(
    default_python_version="PY3",
    name = "softmax_regression",
    srcs = ["softmax_regression.py"],
    srcs_version = "PY3",
)